# ARG that receives the name of the dependency image from the CI pipeline
ARG PACKAGE_IMAGE

# ---- Builder Stage ----
# This stage starts from our pre-built dependency image and builds the Next.js app.
FROM ${PACKAGE_IMAGE} AS builder

# Pass all run-time environment variables
ARG NEXT_PUBLIC_POCKETBASE_URL
ARG NEXT_PUBLIC_DAYS_TO_REFRESH
ARG REDIS_HOST
ARG REDIS_PORT
ARG APP_ENV
ARG POCKETBASE_ADMIN_USERNAME
ARG POCKETBASE_ADMIN_PASSWORD
ARG VAPID_PUBLIC_KEY
ARG VAPID_PRIVATE_KEY
ARG API_URL

ENV NEXT_PUBLIC_POCKETBASE_URL=$NEXT_PUBLIC_POCKETBASE_URL
ENV NEXT_PUBLIC_DAYS_TO_REFRESH=$NEXT_PUBLIC_DAYS_TO_REFRESH
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV NEXT_PUBLIC_API_URL=$API_URL
ENV APP_ENV=$APP_ENV
ENV POCKETBASE_ADMIN_USERNAME=$POCKETBASE_ADMIN_USERNAME
ENV POCKETBASE_ADMIN_PASSWORD=$POCKETBASE_ADMIN_PASSWORD
ENV NEXT_PUBLIC_VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY
ENV VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY
ENV NODE_ENV=production
ENV PORT=3000

WORKDIR /app

# Copy the rest of the project source code
COPY . .

# Build the Next.js application.
# The slow 'apt-get' and 'pnpm install' steps are skipped because they are in the base image.
RUN pnpm build


# ---- Final Stage ----
# This stage creates a lean, production-ready image.
FROM builder AS runner


WORKDIR /app

# Create a non-root user for security
RUN useradd -m appuser


COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --prod --frozen-lockfile

# Copy the built application files from the builder stage
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next

# Change ownership of app files to the non-root user
RUN chown -R appuser:appuser /app

# Switch to the non-root user
USER appuser

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost:${PORT}/ready || exit 1

# Start the Next.js application
CMD ["npm", "start"]