import "@mantine/core/styles.css";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button, createTheme, MantineProvider, px } from "@mantine/core";
import AppShell from "@/components/appShell/AppShell/AppShell";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

// export const metadata: Metadata = {
//     title: "Ketaab Khooneh",
//     description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = createTheme({
    /** Put your mantine theme override here */
  });

  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme} defaultColorScheme="auto">
          <AppShell>{children}</AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}
