import "@mantine/core/styles.css";
import PocketBase from "pocketbase";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button, createTheme, MantineProvider, px } from "@mantine/core";
import AppShell from "@/components/appShell/AppShell/AppShell";

const mainFont = localFont({
  display: "block",
  preload: true,
  adjustFontFallback: "Arial",
  src: [
    {
      path: "../../public/fonts/Barlow/Barlow-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Barlow/Barlow-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/Barlow/Barlow-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Barlow/Barlow-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../../public/fonts/Barlow/Barlow-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Barlow/Barlow-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
  ],
});

// export const metadata: Metadata = {
//     title: "Ketaab Khooneh",
//     description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pb = new PocketBase("http://pocketbase:8080");

  const res = await pb.collection("users").authWithPassword('hossein', 'one+one=one')

  console.log({res})

  const theme = createTheme({
    fontFamily: `${mainFont.style.fontFamily}, Tahoma, sans-serif`,
    components: {
      Text: {
        styles: {
          marginTop: "-1px",
        },
      },
    },
    headings: {
      sizes: {
        h1: {
          fontWeight: "700",
        },
        h2: {
          fontWeight: "700",
          lineHeight: "38px",
        },
        h3: {
          fontWeight: "700",
        },
        h4: {
          fontWeight: "500",
        },
        h5: {
          fontWeight: "500",
        },
        h6: {
          fontWeight: "500",
        },
      },
    },
    fontFamilyMonospace: "Monaco, Courier, monospace",
    /** Put your mantine theme override here */
  });

  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme} defaultColorScheme="auto">
          <AppShell>{children}</AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}
