"use client";
import AppLayout from "@/layouts/AppLayout";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "../globals.css";
import "@tapsioss/theme/css-variables";
import { PWAProvider } from "@/providers/PWAProvider";
import { createTheme, MantineProvider } from "@mantine/core";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Notifications } from "@mantine/notifications";

// export const metadata: Metadata = {
//     title: "Ketaab Khooneh",
//     description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = createTheme({
    fontFamily: `VazirMatn, Tahoma, sans-serif`,
    headings: {
      sizes: {
        h1: {
          fontWeight: "700",
        },
        h2: {
          fontWeight: "700",
          lineHeight: "38px",
        },
        h3: {
          fontWeight: "700",
        },
        h4: {
          fontWeight: "500",
        },
        h5: {
          fontWeight: "500",
        },
        h6: {
          fontWeight: "500",
        },
      },
    },
    fontFamilyMonospace: "Monaco, Courier, monospace",
    /** Put your mantine theme override here */
  });

  const queryClient = new QueryClient();
  return (
    <QueryClientProvider client={queryClient}>
      <MantineProvider theme={theme} defaultColorScheme="light">
        <Notifications />
        <PWAProvider>
          <AppLayout>{children}</AppLayout>
        </PWAProvider>
      </MantineProvider>
    </QueryClientProvider>
  );
}
