name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: . # Use root of project as build context
          file: ./docker-build/Dockerfile # Path to Dockerfile in ./docker-build folder
          push: true
          no-cache: true
          build-args: |
            NEXT_PUBLIC_POCKETBASE_URL=${{ vars.ENV_POCKETBASE_URL }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ketaab-khooneh:latest
            ${{ secrets.DOCKER_USERNAME }}/ketaab-khooneh:${{ github.sha }}

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22 # Default SSH port, adjust if different
          script: |
            cd ./docker
            docker compose pull
            docker compose down
            docker compose up -d --build
