name: Ghafaseh CI/CD

on:
  push:
    branches:
      - main

jobs:
  # This job runs first to check for file changes
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.changes.outputs.backend }}
    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for an accurate diff
      - name: Check for backend changes in the push
        uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ 'origin/main~1' }}
          filters: |
            backend:
              - 'backend/**'
              - '!backend/pb_data/**'
      - name: Print changed files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      - name: Debug paths-filter outputs
        if: steps.changes.outputs.backend == 'true'
        run: |
          echo "Debug: All outputs from the paths-filter step:"
          echo '${{ toJSON(steps.changes.outputs) }}'
          echo '${{ toJSON(github.event) }}'

  # Job to build and push the frontend image
  build_and_push_frontend:
    runs-on: ubuntu-latest
    environment: production
    needs: check_changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker-build/Dockerfile.frontend
          push: true
          build-args: |
            NEXT_PUBLIC_POCKETBASE_URL=${{ vars.ENV_POCKETBASE_URL }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ketaab-khooneh-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/ketaab-khooneh-frontend:${{ github.sha }}

  # Job to build and push the backend image
  build_and_push_backend:
    runs-on: ubuntu-latest
    environment: production
    needs: check_changes
    if: needs.check_changes.outputs.backend_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./docker-build/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ketaab-khooneh-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/ketaab-khooneh-backend:${{ github.sha }}

  # This job waits for both build jobs to complete successfully
  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: [build_and_push_frontend, build_and_push_backend]
    # Run only if dependent jobs succeeded or were skipped, but NOT if they failed.
    if: ${{ !failure() && !cancelled() }}
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            netplan apply
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            cd ./docker
            docker compose pull
            docker compose down
            docker compose up -d --build
            docker image prune -f -a
